[project]
name = "smollm3-sts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "datasets>=4.0.0",
    "numpy>=2.0.2",
    "pandas>=2.3.1",
]
